stages:
  data-processing:
    cmd: python3 scripts/data_scripts/data_processing.py data/raw/exams.csv
    deps:
    - data/raw/exams.csv
    - scripts/data_scripts/data_processing.py
    outs:
    - data/stage1
  split:
    cmd: python3 scripts/data_scripts/train_test_split.py data/stage1/exams.csv
    deps:
    - data/stage1/exams.csv
    - scripts/data_scripts/train_test_split.py
    params:
    - split.split_ratio
    outs:
    - data/stage2
  train:
    cmd: python3 scripts/model_scripts/dt.py data/stage2/train.csv model.pkl
    deps:
    - data/stage2/train.csv
    - scripts/model_scripts/dt.py
    params:
    - train.n_jobs
    - train.fit_intercept
    outs:
    - models/model.pkl
  evaluate:
    cmd: python3 scripts/model_scripts/evaluate.py data/stage2/test.csv models/model.pkl
    deps:
    - data/stage2/test.csv
    - models/model.pkl
    - scripts/model_scripts/evaluate.py
    metrics:
    - evaluate/score.json:
        cache: false
